/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/sms-codes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 发送短信验证码 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SendSmsCodeRequest"];
                };
            };
            responses: {
                /** @description 已发送 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SendSmsCodeResponse"];
                    };
                };
                429: components["responses"]["TooManyRequests"];
                default: components["responses"]["Error"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 手机号验证码登录 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginRequest"];
                };
            };
            responses: {
                /** @description 登录成功；刷新令牌建议通过 HttpOnly Cookie 下发 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Session"];
                    };
                };
                default: components["responses"]["Error"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/sessions/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 使用 HttpOnly Cookie 刷新会话 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 刷新成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Session"];
                    };
                };
                401: components["responses"]["Error"];
                default: components["responses"]["Error"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** 退出登录 */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 已退出 */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                default: components["responses"]["Error"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 读取当前账户 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 账户信息 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Account"];
                    };
                };
                default: components["responses"]["Error"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/wallet": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 读取创作点余额 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 余额与用量 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Wallet"];
                    };
                };
                default: components["responses"]["Error"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/wallet/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 分页读取交易记录 */
        get: {
            parameters: {
                query?: {
                    page?: components["parameters"]["Page"];
                    page_size?: components["parameters"]["PageSize"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 交易记录分页 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TransactionPage"];
                    };
                };
                default: components["responses"]["Error"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 读取平台开放模型
         * @description 仅返回平台已配置且可向当前用户开放的模型目录，不返回供应商凭证或内部连接信息。
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 平台模型目录 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ModelList"];
                    };
                };
                default: components["responses"]["Error"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/uploads/presign": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 获取素材直传凭证 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PresignUploadRequest"];
                };
            };
            responses: {
                /** @description 短期上传地址 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PresignUploadResponse"];
                    };
                };
                413: components["responses"]["PayloadTooLarge"];
                default: components["responses"]["Error"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 分页读取任务 */
        get: {
            parameters: {
                query?: {
                    page?: components["parameters"]["Page"];
                    page_size?: components["parameters"]["PageSize"];
                    status?: components["schemas"]["TaskStatus"];
                    q?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 任务分页 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TaskPage"];
                    };
                };
                default: components["responses"]["Error"];
            };
        };
        put?: never;
        /**
         * 创建生成任务
         * @description 必须携带 Idempotency-Key，扣点和任务创建需在同一事务或可补偿事务中完成。
         */
        post: {
            parameters: {
                query?: never;
                header: {
                    "Idempotency-Key": string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateTaskRequest"];
                };
            };
            responses: {
                /** @description 任务已创建 */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Task"];
                    };
                };
                402: components["responses"]["InsufficientBalance"];
                409: components["responses"]["Conflict"];
                default: components["responses"]["Error"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/{task_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: components["parameters"]["TaskId"];
            };
            cookie?: never;
        };
        /** 读取任务详情 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    task_id: components["parameters"]["TaskId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 任务详情 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Task"];
                    };
                };
                default: components["responses"]["Error"];
            };
        };
        put?: never;
        post?: never;
        /** 删除任务记录 */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    task_id: components["parameters"]["TaskId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 已删除 */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                409: components["responses"]["Conflict"];
                default: components["responses"]["Error"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/{task_id}/result": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: components["parameters"]["TaskId"];
            };
            cookie?: never;
        };
        /** 获取短期播放与下载地址 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    task_id: components["parameters"]["TaskId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 结果地址 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TaskResult"];
                    };
                };
                409: components["responses"]["Conflict"];
                default: components["responses"]["Error"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            /** @example INSUFFICIENT_BALANCE */
            code: string;
            message: string;
            request_id: string;
            details?: {
                [key: string]: unknown;
            } | null;
        };
        SendSmsCodeRequest: {
            phone: string;
            /** @enum {string} */
            scene: "login";
        };
        SendSmsCodeResponse: {
            request_id: string;
            /** @example 300 */
            expires_in: number;
        };
        LoginRequest: {
            phone: string;
            code: string;
        };
        Session: {
            access_token: string;
            expires_in: number;
            user: components["schemas"]["Account"];
        };
        Account: {
            /** @example clzs-7F3A9C2E-20260808 */
            readonly aid: string;
            name: string;
            phone: string;
            /** Format: email */
            email?: string | null;
            avatar_seed: number;
        };
        Wallet: {
            available: number;
            used_this_month: number;
            usage_percent: number;
        };
        Transaction: {
            id: string;
            /** Format: date-time */
            occurred_at: string;
            /** @enum {string} */
            type: "任务消耗" | "套餐发放" | "活动奖励" | "失败退款" | "人工调整";
            reference: string;
            detail?: string;
            /** @description 正数入账，负数扣减 */
            amount: number;
        };
        TransactionPage: components["schemas"]["PageMeta"] & {
            items?: components["schemas"]["Transaction"][];
        };
        ModelCapabilities: {
            aspects: ("16:9" | "9:16" | "1:1" | "4:3")[];
            resolutions: string[];
            durations?: (5 | 10 | 15 | 30)[];
            counts?: (1 | 2 | 4)[];
            sound?: boolean;
            watermark?: boolean;
            reference_image?: boolean;
            reference_video?: boolean;
        };
        Model: {
            /** @description 平台稳定模型标识，创建任务时提交该值 */
            id: string;
            name: string;
            provider_name: string;
            /** @enum {string} */
            mode: "video" | "image";
            /** @enum {string} */
            status: "available" | "maintenance" | "disabled";
            base_points: number;
            capabilities: components["schemas"]["ModelCapabilities"];
        };
        ModelList: {
            items: components["schemas"]["Model"][];
            total: number;
        };
        PresignUploadRequest: {
            file_name: string;
            /** @enum {string} */
            content_type: "image/png" | "image/jpeg" | "image/webp" | "video/mp4" | "video/webm";
            size: number;
        };
        PresignUploadResponse: {
            asset_id: string;
            /** Format: uri */
            upload_url: string;
            headers: {
                [key: string]: string;
            };
            expires_in: number;
        };
        /** @enum {string} */
        TaskStatus: "queued" | "generating" | "done" | "failed" | "cancelled";
        CreateTaskRequest: {
            prompt: string;
            /** @enum {string} */
            mode: "video" | "image";
            /** @description 来自 GET /models 的平台模型标识 */
            model_id: string;
            /** @enum {string} */
            aspect: "16:9" | "9:16" | "1:1" | "4:3";
            resolution: string;
            /** @enum {string} */
            duration?: "5s" | "10s" | "15s" | "30s";
            /** @enum {integer} */
            count?: 1 | 2 | 4;
            sound?: boolean;
            watermark?: string;
            reference_asset_id?: string;
            /** @description 用户确认的本次最高创作点；最终价格由服务端计算且不得超过该值 */
            max_points: number;
        };
        Task: {
            id: string;
            title: string;
            /** @enum {string} */
            mode?: "video" | "image";
            model_id?: string;
            meta: string;
            cost: number;
            status: components["schemas"]["TaskStatus"];
            progress: number;
            image?: string;
            created: string;
            error?: string | null;
        };
        TaskPage: components["schemas"]["PageMeta"] & {
            items?: components["schemas"]["Task"][];
        };
        TaskResult: {
            /** Format: uri */
            playback_url: string;
            /** Format: uri */
            download_url?: string;
            /** Format: uri */
            poster_url?: string;
            /** @example video/mp4 */
            media_type: string;
            /** Format: date-time */
            expires_at: string;
        };
        PageMeta: {
            page: number;
            page_size: number;
            total: number;
        };
    };
    responses: {
        /** @description 统一错误 */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description 请求过于频繁 */
        TooManyRequests: {
            headers: {
                "Retry-After"?: number;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description 资源状态冲突 */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description 文件过大 */
        PayloadTooLarge: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description 创作点不足 */
        InsufficientBalance: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        Page: number;
        PageSize: number;
        TaskId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
